package com.coax.db.dto;
// Generated Mar 7, 2012 11:25:22 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log  implements java.io.Serializable {


     private long rowId;
     private Date dateTime;
     private String nameTable;
     private String err;
     private long userId;
     private String description;
     private Date createDate;

    public Log() {
    }

	
    public Log(long rowId, Date dateTime, String nameTable, String err, long userId) {
        this.rowId = rowId;
        this.dateTime = dateTime;
        this.nameTable = nameTable;
        this.err = err;
        this.userId = userId;
    }
    public Log(long rowId, Date dateTime, String nameTable, String err, long userId, String description, Date createDate) {
       this.rowId = rowId;
       this.dateTime = dateTime;
       this.nameTable = nameTable;
       this.err = err;
       this.userId = userId;
       this.description = description;
       this.createDate = createDate;
    }
   
    public long getRowId() {
        return this.rowId;
    }
    
    public void setRowId(long rowId) {
        this.rowId = rowId;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public String getNameTable() {
        return this.nameTable;
    }
    
    public void setNameTable(String nameTable) {
        this.nameTable = nameTable;
    }
    public String getErr() {
        return this.err;
    }
    
    public void setErr(String err) {
        this.err = err;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    
    public String jsonObject(){
		StringBuilder sBuilder = new StringBuilder();
		/*
		sBuilder.append("{ \""+ Log + "\":\"" + this.getId() +"\",");
		sBuilder.append(" \""+ Historys.c_fileXML + "\":\"" + this.fileXml +"\",");
		sBuilder.append(" \""+ Historys.c_result + "\":\"" + this.result +"\",");
		sBuilder.append(" \""+ Historys.c_selectId + "\":\"" + this.selectId +"\",");
		sBuilder.append(" \""+ Historys.c_status + "\":\"" + this.status +"\",");
		sBuilder.append(" \""+ Historys.c_stepFrom + "\":\"" + this.stepFrom +"\",");
		sBuilder.append(" \""+ Historys.c_stepTo + "\":\"" + this.stepTo +"\",");
		sBuilder.append(" \""+ Historys.c_created_on + "\":\"" + this.createdOn +"\"");
		sBuilder.append("}");
		*/
		return sBuilder.toString();
	}
}


