package com.coax.db.dto;
// Generated Mar 7, 2012 11:25:22 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Logins generated by hbm2java.
 */
/**
 * @author phuctq :Lưu thông tin khi users đăng nhập
 *
 */
public class Logins  implements java.io.Serializable {
	
	/**
	 * Field :id
	 */
	public final static String c_id = "id";
	/**
	 * Field :lastLogin
	 */
	public final static String c_lastLogin ="last_login";
    /**
     * Field :ip
     */
    public final static String c_ip ="ip";
    /**
     * Field : UserId
     */
    public final static String c_userId ="userid";
    /**
     * Field : device
     */
    public final static String c_device ="device";
    /**
     * Field : token
     */
    public final static String c_token ="token";
    
     private long id;
     private Date lastLogin;
     private String ip;
     private long userId;
     private String device;
     private String token;

    public Logins() {
    }

	
    public Logins(long id, long userId) {
        this.id = id;
        this.userId = userId;
    }
    public Logins(long id, Date lastLogin, String ip, long userId, String device, String token) {
       this.id = id;
       this.lastLogin = lastLogin;
       this.ip = ip;
       this.userId = userId;
       this.device = device;
       this.token = token;
    }
   
    public long getId() {
        return this.id;
    }
    
    /**
     * @param id :
     */
    public void setId(long id) {
        this.id = id;
    }
    /**
     * @return
     */
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    /**
     * @param lastLogin :Lần đăng nhập sau cùng
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
    
    /**
     * @return : Lấy địa chỉ ip của máy tính
     */
    public String getIp() {
        return this.ip;
    }
    
    /**
     * @param ip: Gán địa chỉ ip của máy tinh khi truy cập vào
     */
    public void setIp(String ip) {
        this.ip = ip;
    }
    public long getUserId() {
        return this.userId;
    }
    
    /**
     * @param userId : Chứa thông tin id của users
     */
    public void setUserId(long userId) {
        this.userId = userId;
    }
    
    public String getDevice() {
        return this.device;
    }
    
    /**
     * @param device : Gán thiết bị truy cập
     */
    public void setDevice(String device) {
        this.device = device;
    }
    
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    
    /**
     * @return :Trả về kiểu json của đối tượng
     */
    public String jsonObject(){
    	
		StringBuilder sBuilder = new StringBuilder();		
		sBuilder.append("{ \""+ Logins.c_id + "\":\"" + this.getId() +"\",");
		sBuilder.append(" \""+ Logins.c_device + "\":\"" + this.device +"\",");
		sBuilder.append(" \""+ Logins.c_ip + "\":\"" + this.ip +"\",");
		sBuilder.append(" \""+ Logins.c_lastLogin + "\":\"" + this.lastLogin +"\",");
		sBuilder.append(" \""+ Logins.c_token + "\":\"" + this.token +"\",");				
		sBuilder.append(" \""+ Logins.c_userId + "\":\"" + this.userId +"\"");
		sBuilder.append("}");
		
		return sBuilder.toString();
	}
}


