package com.coax.db.dto;
// Generated Mar 7, 2012 11:25:22 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * SelectExercies generated by hbm2java
 */
/**
 * @author phuctq : Lưu trữ bài tập được chọn.Được sinh bởi Hibernate
 *
 */
public class SelectExercies  implements java.io.Serializable {


	/**
	 * Field : id
	 */
	public final static String c_id = "id";
	/**
	 * Field :userId
	 */
	public final static String c_userId ="userId";
    /**
     * Field : exerciseId
     */
    public final static String c_exerciseId = "exerciseId";
    /**
     * Field : laTex
     */
    public final static String c_laTex ="laTex";
    /**
     *Field : fileXML 
     */
    public final static String c_fileXml ="fileXML";
    /**
     * Field :times
     */
    public final static String c_times = "times";
    /**
     * Field :create_on
     */
    public final static String c_createdOn = "created_on";
    
     private long id;
     private long userId;
     private long exerciseId;
     private String laTex;
     private String fileXml;
     private Short times = 1;
     private Date createdOn;

    public SelectExercies() {
    	
    }

    public SelectExercies(long id, long userId, long exerciseId, String laTex, Date createdOn) {
        this.id = id;
        this.userId = userId;
        this.exerciseId = exerciseId;
        this.laTex = laTex;
        this.createdOn = createdOn;
    }
    
    public SelectExercies(long id, long userId, long exerciseId, String laTex, String fileXml, Short times, Date createdOn) {
       this.id = id;
       this.userId = userId;
       this.exerciseId = exerciseId;
       this.laTex = laTex;
       this.fileXml = fileXml;
       this.times = times;
       this.createdOn = createdOn;
    }
   
    public long getId() {
        return this.id;
    }
    
    /**
     * @param id
     */
    public void setId(long id) {
        this.id = id;
    }
    /**
     * @return
     */
    public long getUserId() {
        return this.userId;
    }
    
    /**
     * @param userId
     */
    public void setUserId(long userId) {
        this.userId = userId;
    }
    /**
     * @return
     */
    public long getExerciseId() {
        return this.exerciseId;
    }
    
    public void setExerciseId(long exerciseId) {
        this.exerciseId = exerciseId;
    }
    /**
     * @return
     */
    public String getLaTex() {
        return this.laTex;
    }
    
    /**
     * @param laTex
     */
    public void setLaTex(String laTex) {
        this.laTex = laTex;
    }
    
    /**
     * @return
     */
    public String getFileXml() {
        return this.fileXml;
    }
    
    /**
     * @param fileXml
     */
    public void setFileXml(String fileXml) {
        this.fileXml = fileXml;
    }
    
    public Short getTimes() {
        return this.times;
    }
    
    public void setTimes(Short times) {
        this.times = times;
    }
    
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * @return : Trả về kiểu json cho client
     */
    public String jsonObject(){
    	
		StringBuilder sBuilder = new StringBuilder();		
		sBuilder.append("{ \""+ SelectExercies.c_id + "\":\"" + this.getId() +"\",");
		sBuilder.append(" \"" + SelectExercies.c_laTex + "\":\"" + this.laTex +"\",");
		sBuilder.append(" \"" + SelectExercies.c_exerciseId + "\":\"" + this.exerciseId +"\",");
		sBuilder.append(" \"" + SelectExercies.c_fileXml + "\":\"" + this.fileXml +"\",");
		sBuilder.append(" \"" + SelectExercies.c_times + "\":\"" + this.times +"\",");
		sBuilder.append(" \"" + SelectExercies.c_userId + "\":\"" + this.userId +"\",");
		sBuilder.append(" \"" + SelectExercies.c_createdOn + "\":\"" + this.createdOn +"\"");
		sBuilder.append("}");
		
		return sBuilder.toString();
	}
}


