package com.coax.db.dto;
// Generated Mar 7, 2012 11:25:22 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Setting generated by hbm2java
 */
public class Settings  implements java.io.Serializable {


	public final static String c_Id = "Id";
	public final static String c_userId = "userId";
	public final static String c_configId = "configId";
	public final static String c_name = "name";
	public final static String c_value = "value";
	public final static String c_createdOn = "created_on";
    
     private Long id;
     private Long userId;
     private int configId;
     private String name;
     private String value;
     private Date createdOn;

    public Settings() {
    	
    }
	
    public Settings(int configId, String name, String value) {
        this.configId = configId;
        this.name = name;
        this.value = value;
    }
    
    public Settings(Long userId, int configId, String name, String value, Date createdOn) {
       this.userId = userId;
       this.configId = configId;
       this.name = name;
       this.value = value;
       this.createdOn = createdOn;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    public int getConfigId() {
        return this.configId;
    }
    
    public void setConfigId(int l) {
        this.configId = l;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String isValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    
    public String jsonObject(){
    	
		StringBuilder sBuilder = new StringBuilder();		
	
		sBuilder.append("{ \""+ Settings.c_Id + "\":\"" + this.getId() +"\",");
		sBuilder.append(" \"" + Settings.c_configId + "\":\"" + this.configId +"\",");
		sBuilder.append(" \"" + Settings.c_name + "\":\"" + this.name +"\",");
		sBuilder.append(" \"" + Settings.c_userId + "\":\"" + this.userId +"\",");
		sBuilder.append(" \"" + Settings.c_value + "\":\"" + this.value +"\",");		
		sBuilder.append(" \"" + Settings.c_createdOn + "\":\"" + this.createdOn +"\"");
		sBuilder.append("}");
	
		return sBuilder.toString();
	}

}


