package com.coax.db.dto;
// Generated Mar 7, 2012 11:25:22 PM by Hibernate Tools 3.4.0.CR1

import com.coax.db.dao.UserModeDAO;
import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

///danh sach cac cot trong 
    /**
     * Field : id của users
     */
    public final static String c_Id = "id";
    /**
     * Field :name userName
     */
    public final static String c_name = "name";
    /**
     * Field : password
     */
    public final static String c_password = "password";
    /**
     * Field : email
     */
    public final static String c_email = "email";
    /**
     * Field : fullname
     */
    public final static String c_fullName = "fullName";
    /**
     * Field : status có 3 trạng thái.0 mới đăng ký chưa kịch hoạt,1 đã được kích hoạt,2 tài khoản đó bị cấm quyền truy cập
     */
    public final static String c_status = "status";
    /**
     * Field : User_type chứa id của nhóm users(bảng User_types)
     */
    public final static String c_userType = "user_type";
    /**
     * Field : birthDay chứa ngày sinh của Users
     */
    public final static String c_birthDay = "birthDay";
    /**
     * Field : address
     */
    public final static String c_address = "address";
    /**
     * Field : phone
     */
    public final static String c_phone = "phone";
    public final static String c_createdOn = "created_on";
    public final static String c_usermode = "usermodeid";
    
    private UserMode userMode;
    private int usermodeid=-1;
    private long id;
    private String name;
    private String password;
    private String email;
    private String fullName;
    private Byte status=1;
    private short userType=2;
    private Date birthDay;
    private String address;
    private String phone;
    private java.sql.Date createdOn;
    private UserTypes types = null;

    public Users() {
        this.id = 1;
        this.name = "";
        this.password = "";
        this.email = "";
        this.fullName = "";
        this.status = 1;
        this.userType = 3;
        this.birthDay = new java.sql.Date(1980, 2, 3);
        this.address = "";
        this.phone = "";
        //this.createdOn = createdOn;
    }

    public Users(long id, String name, String password, short userType) {
        this.id = id;
        this.name = name;
        this.password = password;
        this.userType = userType;
    }

    public Users(long id, String name, String password, String email, String fullName, Byte status, short userType, Date birthDay, String address, String phone, Date createdOn) {
        this.id = id;
        this.name = name;
        this.password = password;
        this.email = email;
        this.fullName = fullName;
        this.status = status;
        this.userType = userType;
        //this.birthDay = birthDay;
        this.address = address;
        this.phone = phone;
        //this.createdOn = createdOn;
    }

    public Users(String name, String password, String email, String fullName,
            Date birthDay, String address, String phone) {
        super();
        this.name = name;
        this.password = password;
        this.email = email;
        this.fullName = fullName;
        this.birthDay = birthDay;
        this.address = address;
        this.phone = phone;
    }

    public UserTypes getTypes() {
        return this.types;
    }

    public void setTypes(UserTypes types) {
        this.types = types;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public Byte getStatus() {
        return this.status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public short getUserType() {
        return this.userType;
    }

    public void setUserType(short userType) {
        this.userType = userType;
    }

    public Date getBirthDay() {
        return this.birthDay;
    }

    public void setBirthDay(Date birthDay) {
        this.birthDay = birthDay;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(java.sql.Date createdOn) {
        this.createdOn = createdOn;
    }

    public String toString() {
        String s = "Users";
        return s;
    }

    public String formXML() {
        String s = "";
        StringBuilder sBuilder = new StringBuilder();
        sBuilder.append("<" + this.toString() + ">");

        sBuilder.append("</" + this.toString() + ">");
        s = sBuilder.toString();
        return s;
    }

	/**
	 * @return :Trả về kiểu json
	 */
	public String jsonObject() {
		// TODO Auto-generated method stub
		StringBuilder sBuilder = new StringBuilder();
		sBuilder.append("{ \"" + Users.c_Id + "\":\"").append(this.getId()).append("\",");
                sBuilder.append(" \"" + Users.c_usermode + "\":\"").append(this.getUserMode().getName()).append("\",");
		sBuilder.append(" \"" + Users.c_name + "\":\"").append(this.getName()).append("\",");
		sBuilder.append(" \"" + Users.c_fullName + "\":\"").append(this.fullName).append("\",");
		sBuilder.append(" \"" + Users.c_address + "\":\"").append(this.address).append("\",");
		sBuilder.append(" \"" + Users.c_birthDay + "\":\"").append(this.birthDay).append("\",");
		sBuilder.append(" \"" + Users.c_email + "\":\"").append(this.email).append("\",");
		sBuilder.append(" \"" + Users.c_phone + "\":\"").append(this.phone).append("\",");
		sBuilder.append(" \"" + Users.c_status + "\":\"").append(this.status).append("\",");
		sBuilder.append(" \"" + Users.c_userType + "\":\"").append(this.userType).append("\",");
		sBuilder.append(" \"" + Users.c_createdOn + "\":\"").append(this.createdOn).append("\"");
		sBuilder.append("}");
		return sBuilder.toString();
	}

    /**
     * @return the userMode
     */
    public UserMode getUserMode() {
        
        return UserModeDAO.getUserModeById(this.getUserModeid());
    }

    /**
     * @param userMode the userMode to set
     */
    private void setUserMode(UserMode userMode) {
        this.userMode = userMode;
    }

    /**
     * @return the usermodeid
     */
    public int getUserModeid() {
        return usermodeid;
    }

    /**
     * @param usermodeid the usermodeid to set
     */
    public void setUserModeid(int usermodeid) {
        this.usermodeid = usermodeid;
    }
}
