package com.coax.db.dto;
// Generated Mar 7, 2012 11:25:22 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * UserTypes generated by hbm2java
 */
/**
 * @author phuctq
 * Lưu trữ nhóm users được sinh ra từ Hibernate
 */
public class UserTypes  implements java.io.Serializable {


	public final static String c_Id = "Id";
	public final static String c_type = "type";
	public final static String c_description = "description";
	public final static String c_CreateOn = "created_on";
	
    private short id;
    private String type;
    private String description;
    private Date createdOn;

    public UserTypes() {
    }

	
    public UserTypes(short id, String type) {
        this.id = id;
        this.type = type;
    }
    public UserTypes(short id, String type, String description, Date createdOn) {
       this.id = id;
       this.type = type;
       this.description = description;
       this.createdOn = createdOn;
    }
 
    public String toString(){
    	String s ="";
    	s = s + "{ Id :" + this.id + ", Type :" + this.type +", descrition :" + this.description + "}";
    	return s;
    }
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * @return : trả về kiểu json gởi về phía client xử lý
     */
    public String jsonObject(){
		StringBuilder sBuilder = new StringBuilder();
		sBuilder.append("{ \""+ UserTypes.c_Id + "\":\"" + this.getId() +"\",");
		sBuilder.append(" \""+ UserTypes.c_type + "\":\"" + this.type +"\",");
		sBuilder.append(" \""+ UserTypes.c_description + "\":\"" + this.description +"\",");				
		sBuilder.append(" \""+ UserTypes.c_CreateOn + "\":\"" + this.createdOn +"\"");
		sBuilder.append("}");
		return sBuilder.toString();
	}
}


